# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Live' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'Kingfisher', '~> 3.2.1'
  pod 'SVProgressHUD'

end
